server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/juwondb
    username: juwon
    password: juwon1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  output:
    ansi:
      enabled: always